version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE=${DATABASE}
    volumes:
      - .:/app
  mongo:
    image: mongo
    command: --quiet
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: